package Server;

import org.junit.jupiter.api.Test;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;

class SortTest {

    @Test
    void sort() throws IOException {
        Sort sort = new Sort();
        assertEquals("<SendList><head><next><next><next/><dragonData><name>Jose</name><dAge>900</dAge><dRSpeed>35</dRSpeed><resistence>2</resistence><dClas>Commander</dClas><posx>1</posx><posy>155</posy><id>3</id></dragonData></next><dragonData><name>Jose</name><dAge>1</dAge><dRSpeed>65</dRSpeed><resistence>2</resistence><dClas>Commander</dClas><posx>1</posx><posy>85</posy><id>2</id></dragonData></next><dragonData><name>Kevin</name><dAge>1</dAge><dRSpeed>33</dRSpeed><resistence>1</resistence><dClas>Infantry</dClas><posx>1</posx><posy>15</posy><id>1</id></dragonData></head><large>3</large><leftest>1</leftest></SendList>", sort.sort("selection", "<SendList><head><next><next><next/><dragonData><name>Jose</name><dAge>900</dAge><dRSpeed>35</dRSpeed><resistence>2</resistence><dClas>Commander</dClas><posx>1</posx><posy>100</posy><id>3</id></dragonData></next><dragonData><name>Jose</name><dAge>1</dAge><dRSpeed>65</dRSpeed><resistence>2</resistence><dClas>Commander</dClas><posx>12</posx><posy>100</posy><id>2</id></dragonData></next><dragonData><name>Kevin</name><dAge>1</dAge><dRSpeed>33</dRSpeed><resistence>1</resistence><dClas>Infantry</dClas><posx>50</posx><posy>100</posy><id>1</id></dragonData></head><large>3</large><leftest>1</leftest></SendList>"));
        assertEquals("<SendList><head><next><next><next/><dragonData><name>Jose</name><dAge>1</dAge><dRSpeed>65</dRSpeed><resistence>2</resistence><dClas>Commander</dClas><posx>1</posx><posy>155</posy><id>2</id></dragonData></next><dragonData><name>Jose</name><dAge>900</dAge><dRSpeed>35</dRSpeed><resistence>2</resistence><dClas>Commander</dClas><posx>1</posx><posy>85</posy><id>3</id></dragonData></next><dragonData><name>Kevin</name><dAge>1</dAge><dRSpeed>33</dRSpeed><resistence>1</resistence><dClas>Infantry</dClas><posx>1</posx><posy>15</posy><id>1</id></dragonData></head><large>3</large><leftest>1</leftest></SendList>", sort.sort("insertion", "<SendList><head><next><next><next/><dragonData><name>Jose</name><dAge>900</dAge><dRSpeed>35</dRSpeed><resistence>2</resistence><dClas>Commander</dClas><posx>1</posx><posy>100</posy><id>3</id></dragonData></next><dragonData><name>Jose</name><dAge>1</dAge><dRSpeed>65</dRSpeed><resistence>2</resistence><dClas>Commander</dClas><posx>12</posx><posy>100</posy><id>2</id></dragonData></next><dragonData><name>Kevin</name><dAge>1</dAge><dRSpeed>33</dRSpeed><resistence>1</resistence><dClas>Infantry</dClas><posx>50</posx><posy>100</posy><id>1</id></dragonData></head><large>3</large><leftest>1</leftest></SendList>"));
        assertEquals("<SendList><head><next><next><next/><dragonData><name>Jose</name><dAge>900</dAge><dRSpeed>35</dRSpeed><resistence>2</resistence><dClas>Commander</dClas><posx>1</posx><posy>155</posy><id>3</id></dragonData></next><dragonData><name>Kevin</name><dAge>1</dAge><dRSpeed>33</dRSpeed><resistence>1</resistence><dClas>Infantry</dClas><posx>1</posx><posy>85</posy><id>1</id></dragonData></next><dragonData><name>Jose</name><dAge>1</dAge><dRSpeed>65</dRSpeed><resistence>2</resistence><dClas>Commander</dClas><posx>1</posx><posy>15</posy><id>2</id></dragonData></head><large>3</large><leftest>1</leftest></SendList>", sort.sort("quicksort", "<SendList><head><next><next><next/><dragonData><name>Jose</name><dAge>900</dAge><dRSpeed>35</dRSpeed><resistence>2</resistence><dClas>Commander</dClas><posx>1</posx><posy>100</posy><id>3</id></dragonData></next><dragonData><name>Jose</name><dAge>1</dAge><dRSpeed>65</dRSpeed><resistence>2</resistence><dClas>Commander</dClas><posx>12</posx><posy>100</posy><id>2</id></dragonData></next><dragonData><name>Kevin</name><dAge>1</dAge><dRSpeed>33</dRSpeed><resistence>1</resistence><dClas>Infantry</dClas><posx>50</posx><posy>100</posy><id>1</id></dragonData></head><large>3</large><leftest>1</leftest></SendList>"));
        assertEquals("<SendList><head><next><next><next/><dragonData><name>Jose</name><dAge>900</dAge><dRSpeed>35</dRSpeed><resistence>2</resistence><dClas>Commander</dClas><posx>1</posx><posy>100</posy><id>3</id></dragonData></next><dragonData><name>Jose</name><dAge>1</dAge><dRSpeed>65</dRSpeed><resistence>2</resistence><dClas>Commander</dClas><posx>12</posx><posy>100</posy><id>2</id></dragonData></next><dragonData><name>Kevin</name><dAge>1</dAge><dRSpeed>33</dRSpeed><resistence>1</resistence><dClas>Infantry</dClas><posx>1</posx><posy>250</posy><id>1</id></dragonData></head><large>3</large><leftest>1</leftest></SendList>", sort.sort("btree", "<SendList><head><next><next><next/><dragonData><name>Jose</name><dAge>900</dAge><dRSpeed>35</dRSpeed><resistence>2</resistence><dClas>Commander</dClas><posx>1</posx><posy>100</posy><id>3</id></dragonData></next><dragonData><name>Jose</name><dAge>1</dAge><dRSpeed>65</dRSpeed><resistence>2</resistence><dClas>Commander</dClas><posx>12</posx><posy>100</posy><id>2</id></dragonData></next><dragonData><name>Kevin</name><dAge>1</dAge><dRSpeed>33</dRSpeed><resistence>1</resistence><dClas>Infantry</dClas><posx>50</posx><posy>100</posy><id>1</id></dragonData></head><large>3</large><leftest>1</leftest></SendList>"));
        assertEquals("<SendList><head><next><next><next/><dragonData><name>Jose</name><dAge>900</dAge><dRSpeed>35</dRSpeed><resistence>2</resistence><dClas>Commander</dClas><posx>61</posx><posy>160</posy><id>3</id></dragonData></next><dragonData><name>Jose</name><dAge>1</dAge><dRSpeed>65</dRSpeed><resistence>2</resistence><dClas>Commander</dClas><posx>12</posx><posy>100</posy><id>2</id></dragonData></next><dragonData><name>Kevin</name><dAge>1</dAge><dRSpeed>33</dRSpeed><resistence>1</resistence><dClas>Infantry</dClas><posx>1</posx><posy>250</posy><id>1</id></dragonData></head><large>3</large><leftest>1</leftest></SendList>", sort.sort("avl", "<SendList><head><next><next><next/><dragonData><name>Jose</name><dAge>900</dAge><dRSpeed>35</dRSpeed><resistence>2</resistence><dClas>Commander</dClas><posx>1</posx><posy>100</posy><id>3</id></dragonData></next><dragonData><name>Jose</name><dAge>1</dAge><dRSpeed>65</dRSpeed><resistence>2</resistence><dClas>Commander</dClas><posx>12</posx><posy>100</posy><id>2</id></dragonData></next><dragonData><name>Kevin</name><dAge>1</dAge><dRSpeed>33</dRSpeed><resistence>1</resistence><dClas>Infantry</dClas><posx>50</posx><posy>100</posy><id>1</id></dragonData></head><large>3</large><leftest>1</leftest></SendList>"));
    }
}